# Generated by Django 6.0.4 on 2026-04-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_contact_created_at_contact_linkedin_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
