# Generated by Django 6.0.4 on 2026-04-14 10:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outreach',
            options={'verbose_name_plural': 'outreach records'},
        ),
        migrations.AddField(
            model_name='outreach',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outreach',
            name='approved_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outreach',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outreach',
            name='edited_body',
            field=models.TextField(blank=True, help_text='Human-edited body', null=True),
        ),
        migrations.AddField(
            model_name='outreach',
            name='edited_subject',
            field=models.CharField(blank=True, help_text='Human-edited subject', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='outreach',
            name='reply_detected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outreach',
            name='sendgrid_message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outreach',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='status',
            field=models.CharField(choices=[('drafted', 'Drafted'), ('approved', 'Approved'), ('sent', 'Sent'), ('skipped', 'Skipped'), ('replied', 'Replied'), ('failed', 'Failed')], default='drafted', max_length=20),
        ),
    ]
