# Generated by Django 6.0.4 on 2026-04-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outreach", "0002_alter_outreach_options_outreach_approved_at_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="outreach",
            constraint=models.UniqueConstraint(
                fields=("company", "contact"),
                name="uniq_outreach_company_contact",
            ),
        ),
    ]
