# Generated by Django 6.0.4 on 2026-04-14 10:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='ai_recommendations',
            field=models.TextField(blank=True, help_text='Recommended AI services', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ai_score_reasoning',
            field=models.TextField(blank=True, help_text='LLM explanation for the AI score', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='services_offered',
            field=models.TextField(blank=True, help_text='Services scraped from website', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
