# Generated by Django 6.0.3 on 2026-04-06 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DataSource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataChunkProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
                ('website_response_status', models.CharField(blank=True, max_length=10, null=True)),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('sub_urls', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='DataSource.datasource')),
            ],
        ),
    ]
