# Generated by Django 6.0.3 on 2026-05-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("total_companies_found", models.PositiveIntegerField(default=0)),
                ("email_extracted", models.PositiveIntegerField(default=0)),
                ("total_email_send", models.PositiveIntegerField(default=0)),
                ("total_companies", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("name", "is_deleted")},
            },
        ),
    ]
